[licenses]
version = 2

# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93

# Commented license types are allowed but not currently used
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    # "CC0-1.0",
    "ISC",
    "MIT",
    # "OpenSSL",
    # "Unlicense",
    "Zlib",
]

exceptions = [
    { name = "generational-arena", allow = ["MPL-2.0"] },
    { name = "unicode-ident", allow = ["MIT", "Apache-2.0", "Unicode-3.0"] },
    { name = "icu_collections", allow = ["Unicode-3.0"] },
    { name = "icu_locid", allow = ["Unicode-3.0"] },
    { name = "icu_locid_transform", allow = ["Unicode-3.0"] },
    { name = "icu_locid_transform_data", allow = ["Unicode-3.0"] },
    { name = "icu_normalizer", allow = ["Unicode-3.0"] },
    { name = "icu_normalizer_data", allow = ["Unicode-3.0"] },
    { name = "icu_properties", allow = ["Unicode-3.0"] },
    { name = "icu_properties_data", allow = ["Unicode-3.0"] },
    { name = "icu_provider", allow = ["Unicode-3.0"] },
    { name = "icu_provider_macros", allow = ["Unicode-3.0"] },
    { name = "litemap", allow = ["Unicode-3.0"] },
    { name = "tinystr", allow = ["Unicode-3.0"] },
    { name = "writeable", allow = ["Unicode-3.0"] },
    { name = "yoke", allow = ["Unicode-3.0"] },
    { name = "yoke-derive", allow = ["Unicode-3.0"] },
    { name = "zerofrom", allow = ["Unicode-3.0"] },
    { name = "zerofrom-derive", allow = ["Unicode-3.0"] },
    { name = "zerovec", allow = ["Unicode-3.0"] },
    { name = "zerovec-derive", allow = ["Unicode-3.0"] },
]

[bans]
# Deny multiple versions or wildcard dependencies.
wildcards = "deny"

skip = [
    # abi_stable is using an older version of syn
    { name = "syn", version = "1" },
]

[bans.workspace-dependencies]
duplicates = "deny"
include-path-dependencies = true
unused = "deny"
